services:
  postgres:
    image: 'postgres:18'
    container_name: logistics-postgres
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./infrastructure/postgres/init-multiple-databases.sql:/docker-entrypoint-initdb.d/init-multiple-databases.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

# ... (keep artemis and volumes at the bottom exactly the same)

  artemis:
    image: 'apache/activemq-artemis:2.44.0'
    container_name: logistics-artemis
    ports:
      - '61616:61616' # JMS Port
      - '8161:8161'   # Web Console Port (for monitoring queues)
    environment:
      - 'ARTEMIS_USER=${ARTEMIS_USER}'
      - 'ARTEMIS_PASSWORD=${ARTEMIS_PASSWORD}'

volumes:
  postgres-data: