# ----------------------------------------
# Application Settings
# ----------------------------------------
spring.application.name=shipment-service

server.port=8080

# ----------------------------------------
# PostgreSQL Database Configuration
# ----------------------------------------
# Uses environment variables if present, otherwise defaults to local dev settings
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}