server.port=8081

# Threshold for delay alerting (in minutes)
tracking.rules.delay-threshold-minutes=15
# Shipment Service connection URL for validation
shipment.service.url=http://localhost:8080

# ActiveMQ Artemis Configuration
spring.artemis.mode=native
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=artemis
spring.artemis.password=artemis