package com.logistics.notification.controller;

import com.logistics.notification.entity.DelayAlert;
import com.logistics.notification.repository.DelayAlertRepository;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
@RequestMapping("/api/v1")
@Tag(name = "Alerts", description = "Delay alert retrieval for operational monitoring.")
public class DelayAlertController {

    private final DelayAlertRepository alertRepository;

    public DelayAlertController(DelayAlertRepository alertRepository) {
        this.alertRepository = alertRepository;
    }

    @Operation(summary = "Fetch delay alerts", description = "Returns all persisted delay alerts generated by stale telemetry events.")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Alerts returned successfully", content = @Content(array = @io.swagger.v3.oas.annotations.media.ArraySchema(schema = @Schema(implementation = DelayAlert.class))))
    })
    @GetMapping("/alerts")
    public List<DelayAlert> getAlerts() {
        return alertRepository.findAll();
    }
}